version: "3"
services:
    webapp:
        image: node
        user: ${whoami}
        env_file: .docker_env
        volumes:
            - ${BACKEND_PATH:-../}:/home/node/app
        expose:
            - 3000
        command: "npm run dev"
        ports:
            - 3000:3000

networks:
    overlay:
